name: Notify Slack on 2 Approvals

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 2 approvals
        id: approvals
        run: |
          # GitHubのレビューAPIエンドポイント
          REVIEW_API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"

          # GitHub APIを使用してレビューデータを取得
          reviews=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $REVIEW_API_URL)

          # 承認のカウント
          approve_count=$(echo "$reviews" | jq '[.[] | select(.state == "APPROVED")] | length')

          # 環境変数に承認数をセット
          echo "approve_count=$approve_count" >> $GITHUB_ENV

      - name: Set PR info
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Send notification to Slack
        if: env.approve_count == '2'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Repository: '$REPOSITORY_NAME'\nPR Title: '$PR_TITLE'\nAuthor: '$PR_AUTHOR'\nPR URL: '$PR_URL'"}' ${{ secrets.SLACK_WEBHOOK_URL_2APPROVE }}
